### ISSUE TITLE
sqlay3 flickering

### ISSUE THREAD

**Issue by Jobd0ne** [xXorAa/sQ68Lay#5]
Whilst running certain software , the sqlay3 emulator flickers. Whilst I would say the original hardware too can be seen flickering, this is much worse. attached is a sample. This was running on Linux 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux. 
sqlay3 pre-built binary : a7e4540-(2024-02-07)

**Comment by Jobd0ne** [comment]
https://github.com/xXorAa/sQ68Lay/assets/159623993/7038bdcb-b99d-443e-8a58-5a1e12074b37

**Comment by Jobd0ne** [comment]
https://github.com/xXorAa/sQ68Lay/assets/159623993/45583f46-911d-400b-a5ed-dc0c863a5961
This is a re-encoding of the first video.

**Comment by xXorAa** [comment]
Missing support for screen 2, now fixed!
